version: '3.8'
services:
  hazelcast-node1:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node1
    ports:
      - "5701:5701"
    networks:
      - hazelcast-net
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/hazelcast.xml

  hazelcast-node2:
    image: hazelcast/hazelcast:latest
    container_name: ha
