version: "3.9"
services:
  hazelcast-node1:
    image: hazelcast/hazelcast:5.3.1
    container_name: hazelcast-node1
    networks:
      - hazelcast-network

  hazelcast-node2:
    image: hazelcast/hazelcast:5.3.1
    container_name: hazelcast-node2
    networks:
      - hazelcast-network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hazelcast-app
    depends_on:
      - hazelcast-node1
      - hazelcast-node2
    networks:
      - hazelcast-network
    environment:
      - HAZELCAST_CLUSTER_NAME=hazelcast-cluster
networks:
  hazelcast-network:
